# Generated by Django 5.0.2 on 2024-02-24 07:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InsurancePolicy', '0003_remove_lead_assign_to_remove_lead_customer_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Insurance_Type', models.CharField(max_length=50)),
                ('Company', models.CharField(max_length=50)),
                ('Sub_Policy', models.CharField(max_length=50)),
                ('Policy_Number', models.IntegerField()),
                ('Product_Name', models.CharField(max_length=50)),
                ('Sum_Insured', models.IntegerField()),
                ('OD', models.IntegerField()),
                ('TP', models.IntegerField()),
                ('GST_Rate', models.IntegerField()),
                ('Gross_Premium', models.IntegerField()),
                ('Net_Premium', models.IntegerField()),
                ('Attachment', models.FileField(blank=True, null=True, upload_to='pdfs/')),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='Follow_up_date',
            field=models.DateField(default=datetime.date(2024, 2, 24)),
        ),
        migrations.AlterField(
            model_name='lead',
            name='Follow_up_date',
            field=models.DateField(default=datetime.date(2024, 2, 24)),
        ),
    ]
