# Generated by Django 5.0.2 on 2024-02-24 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InsurancePolicy', '0005_remove_policy_sub_policy_policy_end_date_policy_lob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='Policy_Status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=50),
        ),
    ]
