# Generated by Django 5.0.2 on 2024-02-24 12:37

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InsurancePolicy', '0007_lead_lead_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Claim_Incident_Date', models.DateField(default=datetime.date(2024, 2, 24))),
                ('Claim_Filed_Date', models.DateField(default=datetime.date(2024, 2, 24))),
                ('Claim_Reason', models.CharField(max_length=500)),
                ('Requested_Claim_Amount', models.IntegerField()),
                ('Claim_Status', models.CharField(max_length=500)),
                ('Claim_Final_Paid', models.IntegerField()),
                ('Notes', models.CharField(max_length=500)),
                ('Customer_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InsurancePolicy.customer')),
                ('Product_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InsurancePolicy.policy')),
            ],
        ),
    ]
