# Generated by Django 5.0.2 on 2024-02-24 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InsurancePolicy', '0008_claim'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claim',
            old_name='Customer_Name',
            new_name='Customer_Id',
        ),
        migrations.RenameField(
            model_name='claim',
            old_name='Product_Name',
            new_name='Policy_Id',
        ),
    ]
