# Generated by Django 5.0.2 on 2024-02-27 13:57

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InsurancePolicy', '0009_rename_customer_name_claim_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='Customer_Id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='InsurancePolicy.customer'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='Claim_Filed_Date',
            field=models.DateField(default=datetime.date(2024, 2, 27)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='Claim_Incident_Date',
            field=models.DateField(default=datetime.date(2024, 2, 27)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Follow_up_date',
            field=models.DateField(default=datetime.date(2024, 2, 27)),
        ),
        migrations.AlterField(
            model_name='lead',
            name='Follow_up_date',
            field=models.DateField(default=datetime.date(2024, 2, 27)),
        ),
        migrations.AlterField(
            model_name='policy',
            name='End_Date',
            field=models.DateField(default=datetime.date(2024, 2, 27)),
        ),
        migrations.AlterField(
            model_name='policy',
            name='Start_Date',
            field=models.DateField(default=datetime.date(2024, 2, 27)),
        ),
    ]
