# Generated by Django 5.0.2 on 2024-03-01 20:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InsurancePolicy', '0010_policy_customer_id_alter_claim_claim_filed_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('Phone_No', models.IntegerField()),
                ('Email_Id', models.CharField(max_length=100)),
                ('Password', models.IntegerField()),
                ('Gender', models.CharField(max_length=100)),
                ('Job_Title', models.CharField(max_length=100)),
                ('Job_Location', models.CharField(max_length=100)),
                ('Joining_Date', models.DateField(default=datetime.date(2024, 3, 2))),
                ('Date_Of_Birth', models.DateField(default=datetime.date(2024, 3, 2))),
            ],
        ),
        migrations.AlterField(
            model_name='claim',
            name='Claim_Filed_Date',
            field=models.DateField(default=datetime.date(2024, 3, 2)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='Claim_Incident_Date',
            field=models.DateField(default=datetime.date(2024, 3, 2)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Follow_up_date',
            field=models.DateField(default=datetime.date(2024, 3, 2)),
        ),
        migrations.AlterField(
            model_name='lead',
            name='Follow_up_date',
            field=models.DateField(default=datetime.date(2024, 3, 2)),
        ),
        migrations.AlterField(
            model_name='policy',
            name='End_Date',
            field=models.DateField(default=datetime.date(2024, 3, 2)),
        ),
        migrations.AlterField(
            model_name='policy',
            name='Start_Date',
            field=models.DateField(default=datetime.date(2024, 3, 2)),
        ),
    ]
