# Generated by Django 5.0.2 on 2024-03-04 06:06

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InsurancePolicy', '0012_user_profile_alter_claim_claim_filed_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='FirstName',
        ),
        migrations.AddField(
            model_name='user_profile',
            name='User_Id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='claim',
            name='Claim_Filed_Date',
            field=models.DateField(default=datetime.date(2024, 3, 4)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='Claim_Incident_Date',
            field=models.DateField(default=datetime.date(2024, 3, 4)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Follow_up_date',
            field=models.DateField(default=datetime.date(2024, 3, 4)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Date_Of_Birth',
            field=models.DateField(default=datetime.date(2024, 3, 4)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Joining_Date',
            field=models.DateField(default=datetime.date(2024, 3, 4)),
        ),
        migrations.AlterField(
            model_name='lead',
            name='Follow_up_date',
            field=models.DateField(default=datetime.date(2024, 3, 4)),
        ),
        migrations.AlterField(
            model_name='policy',
            name='End_Date',
            field=models.DateField(default=datetime.date(2024, 3, 4)),
        ),
        migrations.AlterField(
            model_name='policy',
            name='Start_Date',
            field=models.DateField(default=datetime.date(2024, 3, 4)),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Date_of_Birth',
            field=models.DateField(default=datetime.date(2024, 3, 4)),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='FatherDOB',
            field=models.DateField(default=datetime.date(2024, 3, 4)),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='MotherDOB',
            field=models.DateField(default=datetime.date(2024, 3, 4)),
        ),
    ]
